analyzer:
  exclude:
    - bricks/**

linter:
  rules:
    always_declare_return_types: true
    unnecessary_await_in_return: true
    prefer_single_quotes: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    avoid_print: true
    always_use_package_imports: true
    cancel_subscriptions: true
    use_super_parameters: true
