name: coopartila_workspace
# sdkPath: .fvm/flutter_sdk
command:
  bootstrap:
    hooks:
      post: |
        dart pub global activate full_coverage

packages:
  - ./**

scripts:
  analyze:
    description: analyze.
    exec: "flutter analyze --no-fatal-infos"

  format:
    description: format files.
    exec: "dart format --set-exit-if-changed ."

  get:
    description: downloads pub packages.
    exec: "flutter pub get"

  test:
    description: test all packages.
    exec: "flutter test --no-pub --coverage"
    packageFilters:
      dirExists:
        - test
      failFast: true

  build-dev:
    description: Build DEVELOPMENT APK.
    exec: "flutter build apk --split-per-abi --dart-define-from-file=dev.env  -t lib/main_dev.dart"

  build-prod:
    description: Build PRODUCTION APK.
    exec: "flutter build apk --split-per-abi --dart-define-from-file=.env  -t lib/main_prod.dart"
