name: coopartila_workspace
# sdkPath: .fvm/flutter_sdk
command:
  bootstrap:
    hooks:
      post: |
        dart pub global activate full_coverage

packages:
  - ./**

scripts:
  analyze:
    description: analyze.
    exec: "flutter analyze --no-fatal-infos"

  format:
    description: format files.
    steps:
      - dart format --set-exit-if-changed ./app
      - dart format --set-exit-if-changed ./core_module
      - dart format --set-exit-if-changed ./dashboard
      - dart format --set-exit-if-changed ./design_system

  get:
    description: downloads pub packages.
    exec: "flutter pub get"

  test:
    description: test all packages.
    exec: "flutter test --no-pub --coverage"
    packageFilters:
      dirExists:
        - test
      failFast: true
  
  ci:
    description: Run CI.
    steps:
      - dart run melos run format
      - dart run melos run analyze
      - dart run melos run test

  build-apk-dev:
    description: Build DEVELOPMENT APK.
    run: "cd app && flutter build apk --split-per-abi --dart-define-from-file=dev.env  -t lib/main_dev.dart"

  build-apk:
    description: Build PRODUCTION APK.
    run: "cd app && flutter build apk --split-per-abi --dart-define-from-file=.env  -t lib/main_prod.dart"

  build-ios-dev:
    description: Build DEVELOPMENT APK.
    run: "cd app && flutter build ios --split-per-abi --dart-define-from-file=dev.env  -t lib/main_dev.dart"

  build-ios:
    description: Build PRODUCTION APK.
    run: "cd app && flutter build ios --split-per-abi --dart-define-from-file=.env  -t lib/main_prod.dart"
