name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flutter_analysis:
    name: Analyze flutter code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Flutter Version
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze --no-fatal-infos

  flutter_format:
    name: Format flutter code
    runs-on: ubuntu-latest
    needs: flutter_analysis
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Flutter Version
        run: flutter --version

      - name: Format code
        run: flutter format --fix .
