name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flutter_ci:
    name: Format flutter code
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          version: 3.22.0

      - name: Install melos
        run: dart pub global activate melos

      - name: bootstraping
        run: dart run melos bootstrap

      - name: format
        run: |
          dart format --set-exit-if-changed ./app
          dart format --set-exit-if-changed ./core_module
          dart format --set-exit-if-changed ./dashboard
          dart format --set-exit-if-changed ./design_system

      - name: analyze
        run: dart run melos run analyze --no-select

      - name: test
        run: dart run melos test --no-select
